<a href="https://colab.research.google.com/github/mkshowhardo/Google-colab/blob/main/one_hot_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as  np
import pandas as pd

In [3]:
df = pd.read_csv('cars.csv')

In [4]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   brand          8128 non-null   object
 1   km_driven      8128 non-null   int64
 2   fuel           8128 non-null   object
 3   owner          8128 non-null   object
 4   selling_price  8128 non-null   int64
dtypes: int64(2), object(3)
memory usage: 317.6+ KB

In [7]:
df.describe()

          km_driven  selling_price
count  8.128000e+03   8.128000e+03
mean   6.981951e+04   6.382718e+05
std    5.655055e+04   8.062534e+05
min    1.000000e+00   2.999900e+04
25%    3.500000e+04   2.549990e+05
50%    6.000000e+04   4.500000e+05
75%    9.800000e+04   6.750000e+05
max    2.360457e+06   1.000000e+07

In [8]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [10]:
df['brand'].nunique()

32

In [11]:
df['brand'].unique()

array(['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault',
       'Mahindra', 'Tata', 'Chevrolet', 'Fiat', 'Datsun', 'Jeep',
       'Mercedes-Benz', 'Mitsubishi', 'Audi', 'Volkswagen', 'BMW',
       'Nissan', 'Lexus', 'Jaguar', 'Land', 'MG', 'Volvo', 'Daewoo',
       'Kia', 'Force', 'Ambassador', 'Ashok', 'Isuzu', 'Opel', 'Peugeot'],
      dtype=object)

In [13]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

# one hot encoding using pandas

In [15]:
pd.get_dummies(df, columns=['fuel', 'owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

k-1 one hot encoding

In [16]:
pd.get_dummies(df, columns=['fuel','owner'], drop_first= True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

one hot encoding using sklearn

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,0:4], df.iloc[:,-1], test_size= 0.3, random_state= 0)

In [36]:
x_train

           brand  km_driven    fuel         owner
5224        Tata      20000  Petrol   First Owner
520       Maruti      30000  Petrol   First Owner
36        Maruti      15000  Petrol   First Owner
5782        Ford      53000  Diesel   First Owner
6522   Chevrolet     120000  Diesel   First Owner
...          ...        ...     ...           ...
4931        Tata      70000  Diesel   Third Owner
3264        Ford     100000  Diesel  Second Owner
1653     Hyundai      90000  Petrol  Second Owner
2607  Volkswagen      90000  Diesel   First Owner
2732     Hyundai     110000  Petrol   First Owner

[5689 rows x 4 columns]

In [40]:
from sklearn.preprocessing import OneHotEncoder

In [46]:
ohe = OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)

In [47]:
x_train_new = ohe.fit_transform(x_train[['fuel','owner']])

In [48]:
x_test_new = ohe.transform(x_test[['fuel','owner']])

In [52]:
x_train_new

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]], dtype=int32)

In [53]:
x_train_new.shape

(5689, 7)

In [57]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new))

array([['Tata', 20000, 0, ..., 0, 0, 0],
       ['Maruti', 30000, 0, ..., 0, 0, 0],
       ['Maruti', 15000, 0, ..., 0, 0, 0],
       ...,
       ['Hyundai', 90000, 0, ..., 1, 0, 0],
       ['Volkswagen', 90000, 1, ..., 0, 0, 0],
       ['Hyundai', 110000, 0, ..., 0, 0, 0]], dtype=object)

one hot encoding for top categores

In [58]:
counts = df['brand'].value_counts()

In [61]:
df['brand'].nunique()
threshold = 100

In [79]:
repl = counts[counts <= threshold].index

In [77]:
import pandas as pd

In [78]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
7462,False,False,False,False,False,True,False,False,False,False,False,False,False
4241,False,False,False,False,False,False,True,False,False,False,False,False,False
5987,False,False,False,False,False,False,True,False,False,False,False,False,False
3271,False,False,False,False,True,False,False,False,False,False,False,False,False
875,False,False,False,False,False,True,False,False,False,False,False,False,False